package com.jfinal.api;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBorrow<M extends BaseBorrow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}
	
	public void setCdId(java.lang.Integer cdId) {
		set("cdId", cdId);
	}
	
	public java.lang.Integer getCdId() {
		return get("cdId");
	}

	public void setPsnlId(java.lang.Integer psnlId) {
		set("psnlId", psnlId);
	}

	public java.lang.Integer getPsnlId() {
		return get("psnlId");
	}
	
	public void setBorrowDate(java.util.Date borrowDate) {
		set("borrowDate", borrowDate);
	}
	
	public java.util.Date getBorrowDate() {
		return get("borrowDate");
	}
	
	public void setBackDate(java.util.Date backDate) {
		set("backDate", backDate);
	}
	
	public java.util.Date getBackDate() {
		return get("backDate");
	}

}
