package com.jfinal.api;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
/**
 * @Description: 借阅人信息
 * @author H
 * @date 2021-05-13 03:33:11
*/
@SuppressWarnings("serial")
public abstract class BasePersonal<M extends BasePersonal<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phoneNumber", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("phoneNumber");
	}

}
