package com.jfinal.api;

import com.jfinal.api.BaseCd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Borrow extends BaseBorrow<Borrow> {
	public static final Borrow dao = new Borrow();
}
