package com.jfinal.api;

import com.jfinal.api.BaseCd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cd extends BaseCd<Cd> {
	public static final Cd dao = new Cd();
}
