package com.jfinal.api;

import com.jfinal.api.BasePersonal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Personal extends BasePersonal<Personal> {
	public static final Personal dao = new Personal();
}
